version: "3.3"

services:
  nginx:
    image: nginx:latest 
    ports:
      - "8081:80"
    volumes:
      - ../src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./php/
      dockerfile: php-fpm.dockerfile
    image: php:fpm
    volumes:
      - ../src:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - '../mysqldata:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin:latest
    ports: 
      - "8082:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    depends_on:
      - mariadb
